basic_app/urls.py
from django.urls import path
from . import views 
from django.conf import settings 
from django.conf.urls.static import static

app_name = 'basic_app' 

urlpatterns = [
      
    path('', views.home.as_view(), name='home'),  
    path('recipies', views.postlist.as_view(), name='recipies'),  
    path('detail/<int:pk>/', views.postdetail.as_view(), name='detail'),
    path('recipies/detail/<int:pk>/', views.postdetail.as_view(), name='detail'),
    path('explore', views.randomlist.as_view(), name='randomlist'),  
    path('Contact', views.contact.as_view(), name='contact'),
    # path('About', views.about.as_view(), name='about'),
    path('ingredients', views.ingredients_list.as_view(), name='ingredients'),
    path('ingredients/<int:pk>/', views.ingredients_detail.as_view(), name='ingdetail'),
    path('search/', views.search, name='search'),
    path('search/detail/<int:pk>', views.postdetail.as_view(), name='detailse'),
    # path('starlist/<int:pk>/', views.stardetail.as_view(), name='stardetail'),
    # path('starlist/<int:x>/detail<int:pk>/', views.basicdetail.as_view(), name='detail'),
    # path('channel/', views.channellist.as_view(), name='channellist'),
    # path('channel/detail/<int:pk>/', views.channeletail.as_view(), name='channeldetail'),
    # path('channel/detail/<int:x>/detail<int:pk>/', views.basicdetail.as_view(), name='detail'),

 
]     

myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static 
from basic_app import views

urlpatterns = [
    path('', include('basic_app.urls')),
    path('admin/', admin.site.urls),

]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

basic_app/models.py
from django.db import models

class Ingredients(models.Model):
    title = models.CharField(max_length=75)

    def __str__(self):
       return self.title


       


class Post(models.Model):   
    title = models.CharField(max_length=75)
    image1 = models.ImageField(upload_to='images/' )    
    image2 = models.ImageField(upload_to='images/' ) 
    image3 = models.ImageField(upload_to='images/' ) 
    image4 = models.ImageField(upload_to='images/' )  
    image5= models.ImageField(upload_to='images/'  )   
    image6 = models.ImageField(upload_to='images/' )   
    image7 = models.ImageField(upload_to='images/' )   
    text_one = models.TextField()
    text_two = models.TextField()
    text_three = models.TextField()
    ingredients_list = models.TextField(max_length= 1500)
    ingredients = models.ManyToManyField(Ingredients)
    text_four = models.TextField()
    summary = models.TextField()
    video = models.FileField(upload_to='videos/')

    def __str__(self):
       return self.title

basic_app/views.py
from django.views.generic import ListView , TemplateView , View, DetailView
from . import models
from django.db.models import Q
from django.core.paginator import Paginator
from basic_app.models import Post , Ingredients
from django.shortcuts import get_object_or_404, render ,reverse


class home(ListView):
    template_name = 'basic_app/home.html'
    context_object_name = 'posts' 
    model = Post
   
    def get_queryset(self):
        return Post.objects.order_by('-id')[:6]
       
    
class postlist(ListView):
    context_object_name = 'postlist'
    model = Post
    template_name = 'basic_app/postlist.html'
    paginate_by = 10
      

       
class postdetail(DetailView):
    context_object_name = 'postdetail'
    model = Post
    template_name = 'basic_app/postdetail.html'
 

    
class randomlist(ListView):
    context_object_name = 'randomlist'
    model = Post
    template_name = 'basic_app/randomlist.html'
        
    def get_queryset(self):
        return Post.objects.order_by('?')
       


class contact(TemplateView):
     template_name = 'basic_app/contact.html'
     




class ingredients_list(ListView): 
    context_object_name = 'inglist'
    model = Ingredients
    template_name = 'basic_app/ingredients.html'


class ingredients_detail(ListView):
     model = Post
     template_name = 'basic_app/ingredients_detail.html'
     context_object_name = 'posts'

     
     def get_queryset(self):
        self.ing = get_object_or_404(Ingredients,pk=self.kwargs['pk'])
        return  Post.objects.filter(ingredients =self.ing)


     def get_context_data(self , **kwargs):
         context = super(ingredients_detail , self).get_context_data(**kwargs)
         context['ingredients'] = self.ing 
         return context

 
def search(request):
     template = 'basic_app/search.html'
     query = request.GET.get('q')
     if query :
         results = Post.objects.filter(Q(title__icontains=query)|
          Q(ingredients_list__icontains=query) )
     else:     
          results = Post.objects.all()
     paginator = Paginator(results, 11)
     
     page_number = request.GET.get('page')
     page_obj = paginator.get_page(page_number)

     return render(request, template , {'page_obj': page_obj , 'query':query})

basic_app/templates/basic_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
     integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans+Narrow&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display+SC:ital,wght@1,400;1,700&display=swap"
    rel="stylesheet">
    <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>



     <link rel="stylesheet" href="{% static '/basic_app/css/base.css' %}" type="text/css" />
    <script src="https://kit.fontawesome.com/89b81721e4.js" crossorigin="anonymous"></script>
  
    
    
    <title>CherryOnTopBakery</title>
</head>
<body>
   
<nav class="navbar  navbar-expand-md  justify-content-center  navbar-light">
    <!-- Brand -->
     <a class="navbar-brand" href="{% url 'basic_app:home' %}"><img src="{% static 'basic_app/images/logoimgg.jpeg' %}" height="80" alt=""><p> <span>C</span>herry<span>O</span>n<span>T</span>op</p>
     </a>


    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
         <ion-icon class="burger" name="menu-outline"></ion-icon>
    </button>

    <!-- Navbar links -->
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="nav justify-content-center">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'basic_app:ingredients' %}">Ingredients</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'basic_app:randomlist' %}">Explore</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'basic_app:contact' %}">Contact</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'basic_app:recipies' %}">View All</a>
            </li>
            
        </ul>
    </div>
 
</nav>
    <form class="form-inline" method="GET" action="/search">
        <input class="form-control mr-sm-2" name="q" value="{{ request.GET.q }}" placeholder="Search__">
        <button class="btn searchbtn " type="submit">Search</button>
    </form>


    {% block content %}
    {% endblock %}


    <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

basic_app/templates/basic_app/contact.html
{% extends 'basic_app/base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'basic_app/css/postdetail.css' %}" type="text/css" />

<h3 class="contact"> contact - </h3>
<div class="contactbox">
<a href="https://www.instagram.com/cherryontop_12m/"> instagram <p class="icons"> <ion-icon name="logo-instagram"></ion-icon></p> </a>
<a href=" https://www.gmail.com/cherryontop12m"> email <p class="icons"> <ion-icon name="mail"></ion-icon> </p> </a>
<a href="https://www.pinterest.com/CherryOnTop/"> pintrest <p class="icons"> <ion-icon name="logo-pinterest"></ion-icon></p> </a>

</div>




    {% endblock %}

basic_app/templates/basic_app/home.html
{% extends 'basic_app/base.html' %}
{% load static %}
{% block content %}

<div class="desbox">
    <P class="featured"> <span>F</span>eatured <span>R</span>ecipes-</P>
</div>
    
<div class="latest">
    {% for post in posts|slice:":2"%}
    <a href=" detail/{{ post.id }}"><img src="{{ post.image1.url }}" alt=""> 
    <u><b> {{post.title}} </b></u></a>
    {% endfor %}
</div>

<div class="desbox">
     <P class="MOSTV"> <span>M</span>OST <span>V</span>IEWED-</P>
 </div>
<!-- 
 carousel container___________________________________________________ -->
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
<div class="carousel-inner">
<div class="carousel-item active">
{% for post in posts|slice:":1"%}
<a href=" detail/{{ post.id }}"><img src="{{ post.image1.url }}" alt="">

</a>
{% endfor %}
</div>
{% for post in posts|slice:"1:6"%}
<div class="carousel-item">
            <a href=" detail/{{ post.id }}"><img src="{{ post.image1.url }}" alt="">
            </a>
</div>
{% endfor %}
        
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>


<P class="MOSTR"> <span>M</span>OST <span>R</span>ECENT-</P>
    <p class="sweet"> YOUR SWEET TOOTH PLACE-</p>

<div class="container-fluid mrcontainer">
    <div class="mostrecent">
    <div class="d-flex flex-wrap">
        {% for post in posts|slice:"3:5" %}
        
        <div class="mritems">
            <a href=" detail/{{ post.id }}"><img src="{{ post.image1.url }}" alt=""></a>
            <p> {{ post.summary|slice:":100" }}  ...... <br> <a href=" detail/{{ post.id }}">View More</a></p>
        </div>
        
        
        {% endfor %}  
     </div>
      
    </div>

    
   
</div>

<p class="vrbutton"> 
<a  href=" {% url 'basic_app:recipies' %}"><button> View All Recipies </button></a>
  </p>



<div class="desbox2">
    <P class="hometitle"> <span>C</span>HERRY <span>O</span>N <span>T</span>OP-</P>
    <p class="titledes">
        Metaphorically means that something special is added to something else that is also very nice to make it just
        much more
        enriched.
        Hi! I'm Sakina.To begin with my story of starting to bake is not out of the way very different but it has to
        eventually
        begin with my MOM!
        Growing up she would get cake boxes to be particular BETTY CROCKER and I would love eating them seeing her I too
        started
        baking. Well Well ended up burning the bottom of the cake and that's why let me tell you there is one thing that
        baking
        for sure teaches you is getting used to burns!!
        Looking at youtube videos and TV channels I became so obsessed about baking that my mom was tired of me but you
        see it
        was not my fault but my mom's.

        Thats alot of reading so lets come to the main point.
        This website basically includes all of my own tried and tested recipes that I am sure you are 100% going to love
        !!
        So guys this is
        "CHERRY ON TOP"
    </p>


    
</div>


{% endblock %}

basic_app/templates/basic_app/ingredients.html
{% extends 'basic_app/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'basic_app/css/postdetail.css' %}" type="text/css" />

<div class=" linkbox ">
    {%  for ingredients in inglist %}
    <a href="{%url 'basic_app:ingredients' %}/{{ingredients.id}}">
            {{ ingredients.title }}
        </a>
   
    {% endfor %}




</div>






{% endblock %}

basic_app/templates/basic_app/ingredients_detail.html
{% extends 'basic_app/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'basic_app/css/postdetail.css' %}" type="text/css" />




<div class="desbox">
    <p class="ingtitle"> {{ingredients.title}}- is the ingredient </p>
</div>


<br>
<br>
<div class="container containerlist">
    {% for post in posts reversed %}
    <a href="{%url 'basic_app:home' %}detail/{{ post.id }}">
        <img src="{{ post.image1.url }}" alt="">
        <p> {{ post.title }}</p>
    </a>
    {% endfor %}
</div>

<!-- 
<p class="ingtitle">  {{ingredients.title}}- is the ingredient   </p>
<div class="container">
    <div class="grid-container-list">
        {% for post in posts reversed %}
        <div class="grid-item">
            <a href="{%url 'basic_app:home' %}detail/{{ post.id }}">
                <img src="{{ post.image1.url }}" alt="">
                <p> {{ post.title }}</p>
            </a>
        </div>
        {% endfor %}
    </div>


</div>

 -->

{% endblock %}

basic_app/templates/basic_app/postdetail.html
{% extends 'basic_app/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'basic_app/css/postdetail.css' %}" type="text/css" />
<br><br>

<div class="postd">   
    
<div class="title">
    <img src="{{ postdetail.image1.url}}" alt="">
    <p class="titletext">
        <u> {{ postdetail.title}} </u> </p>
</div>
<br>

    <div class="content" > 
    {{ postdetail.text_one|safe }}
    </div>
<br>

<div class="subtitle">
    <img src="{{ postdetail.image2.url }}" alt="">
    <img src="{{ postdetail.image3.url }}" alt="">
</div>
<br>


<div class="content">
    {{ postdetail.text_two|safe }}
</div> 
<br>


 <br>
<div class="subtitle">
    <img src="{{ postdetail.image4.url }}" alt="">
    <img src="{{ postdetail.image5.url }}" alt="">
</div>
<br>

<div>
    <video class="videofile"width="200" height="300" src="{{ postdetail.video.url }}" controls autoplay  ></video>

</div>
<br>


<div class="content">
    {{ postdetail.text_three|safe }}
</div>
<br>


<div class="subtitle">
    <img src="{{ postdetail.image6.url }}" alt="">
    <img src="{{ postdetail.image7.url }}" alt="">
</div>
<br>

<div class="content">
{{ postdetail.ingredients_list|safe }}
</div>
<br>

<div class="content">
    {{ postdetail.text_four|safe }}

</div>


 <br> 





</div>



{% endblock %}

basic_app/templates/basic_app/postlist.html
{% extends 'basic_app/base.html' %}
{% load static %}
{% block content %}

<div class="desbox">
    <p>      All Posts -</p>
</div>

<div class="container containerlist">
        {% for post in postlist reversed %}
            <a href="detail/{{ post.id }}">
                <img src="{{ post.image1.url }}" alt="">
                  <p > {{ post.title }}</p>
            </a>
        {% endfor %}
    </div>
</div>


<div  class="pagebtn">   
{% if is_paginated %}
{% if page_obj.has_previous %}
<button class=" pagebutton"> <a href="?page=1"> first page</a></button>
<button class=" pagebutton"> <a href="?page={{page_obj.previous_page_number}}">previous page</a></button>
<button class=" pagebutton"> {{ page_obj.number}}</button>
{% endif %}

{% if page_obj.has_next %}
<button class=" pagebutton"> <a href="?page={{page_obj.next_page_number }}"> next page</a></button>
{% endif %}
{% endif %}


</div>

{% endblock %}

basic_app/templates/basic_app/randomlist.html
{% extends 'basic_app/base.html' %}
{% load static %}
{% block content %}




<div class="desbox">
    <p>Chose from a random list of recipes </p>
</div>
<div class="searchimg">
    {% for post in randomlist|slice:":10" %}
            <a href="detail/{{ post.id }}">
                <img src="{{ post.image1.url }}" alt="">
                <p> {{ post.title }}</p>
            </a>
        {% endfor %}
        </div>

{% endblock %}

basic_app/templates/basic_app/search.html
{% extends 'basic_app/base.html' %}
{% load static %}
{% block content %}
<br>


{% if not page_obj%}
<div class=" jumbotron">
    
        <p> Sorry there are no articles related to this search -</p>
</div>
{% endif %}
  <div class="searchimg">

{% for post in page_obj reversed %}
<a href="detail/{{ post.id }}">
    <img src="{{ post.image1.url }}" alt="">
    <p> {{ post.title }}</p>
</a>
{% endfor %}

  </div>
       





<div class="pagination">
    
        {% if page_obj.has_previous %}
        <button class="pagebutton"> <a href="?page=1&q={{ query }}">&laquo; first</a> </button>
        <button class="pagebutton"> <a href="?page={{ page_obj.previous_page_number }}&q={{ query }}">previous</a>
          </button>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <button class="pagebutton"> <a href="?page={{ page_obj.next_page_number }}&q={{ query }} ">next</a> </button>
        <button class="pagebutton"><a href="?page={{ page_obj.paginator.num_pages }}&q={{ query }}">last &raquo;</a> </button>
       
        {% endif %}
       
        </div>




{% endblock %}